In [1]:
import os
import gc
import re
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, f1_score
from xgboost import XGBClassifier, XGBRegressor
from collections import Counter

c:\Users\Jarvis\anaconda3\envs\machine_learning\lib\site-packages\pkg_resources\__init__.py:126: PkgResourcesDeprecationWarning: 0.996-ko-0.9.2-msvc is an invalid version and will not be supported in a future release
  PkgResourcesDeprecationWarning,


In [2]:
# Data Loading (수술 時 사망 데이터)
data=pd.read_csv("https://raw.githubusercontent.com/GonieAhn/Data-Science-online-course-from-gonie/main/Data%20Store/example_data.csv")

In [3]:
data.describe()

censor        event         age        wtkg        hemo  \
count  532.000000   532.000000  532.000000  532.000000  532.000000   
mean     0.340226   801.236842   35.225564   76.061855    0.078947   
std      0.474231   326.887929    8.852094   13.224698    0.269910   
min      0.000000    33.000000   13.000000   47.401000    0.000000   
25%      0.000000   535.750000   29.000000   67.500000    0.000000   
50%      0.000000   933.500000   34.000000   74.600000    0.000000   
75%      1.000000  1081.000000   40.000000   83.502000    0.000000   
max      1.000000  1231.000000   70.000000  149.000000    1.000000   

             homo       drugs      karnof      oprior         z30  ...  \
count  532.000000  532.000000  532.000000  532.000000  532.000000  ...   
mean     0.640977    0.118421   95.432331    0.030075    0.546992  ...   
std      0.480165    0.323410    5.981856    0.170955    0.498255  ...   
min      0.000000    0.000000   70.000000    0.000000    0.000000  ...   
25%      0.000000    0.000000   90.000000    0.000000    0.000000  ...   
50%      1.000000    0.000000  100.000000    0.000000    1.000000  ...   
75%      1.000000    0.000000  100.000000    0.000000    1.000000  ...   
max      1.000000    1.000000  100.000000    1.000000    1.000000  ...   

           gender        str2       strat     symptom        cd40       cd420  \
count  532.000000  532.000000  532.000000  532.000000  532.000000  532.000000   
mean     0.812030    0.580827    1.981203    0.167293  353.204887  336.139098   
std      0.391056    0.493888    0.905946    0.373589  114.105253  130.961573   
min      0.000000    0.000000    1.000000    0.000000  103.000000   49.000000   
25%      1.000000    0.000000    1.000000    0.000000  271.000000  243.750000   
50%      1.000000    1.000000    2.000000    0.000000  346.000000  330.500000   
75%      1.000000    1.000000    3.000000    0.000000  422.000000  418.000000   
max      1.000000    1.000000    3.000000    1.000000  771.000000  909.000000   

            cd496           r         cd80        cd820  
count  532.000000  532.000000   532.000000   532.000000  
mean   173.146617    0.603383   987.250000   928.214286  
std    191.455406    0.489656   475.223907   438.569798  
min     -1.000000    0.000000   221.000000   150.000000  
25%     -1.000000    0.000000   653.250000   626.500000  
50%    113.000000    1.000000   881.000000   818.000000  
75%    324.000000    1.000000  1190.000000  1164.000000  
max    857.000000    1.000000  4255.000000  3130.000000  

[8 rows x 23 columns]

In [4]:
# Feature Name Cleaning
regex = re.compile(r"\[|\]|<", re.IGNORECASE)
data.columns = [regex.sub("_", col) if any(x in str(col) for x in set(('[', ']', '<'))) else col for col in data.columns.values]

In [5]:
data.columns

Index(['censor', 'event', 'age', 'wtkg', 'hemo', 'homo', 'drugs', 'karnof',
       'oprior', 'z30', 'zprior', 'preanti', 'race', 'gender', 'str2', 'strat',
       'symptom', 'cd40', 'cd420', 'cd496', 'r', 'cd80', 'cd820'],
      dtype='object')

In [6]:
# Data Quality Checking
col = []
missing = []
level = [] 
for name in data.columns:
    
    # Missing
    missper = data[name].isnull().sum() / data.shape[0]
    missing.append(round(missper, 4))

    # Leveling
    lel = data[name].dropna()
    level.append(len(list(set(lel))))

    # Columns
    col.append(name)

summary = pd.concat([pd.DataFrame(col, columns=['name']), 
                     pd.DataFrame(missing, columns=['Missing Percentage']), 
                     pd.DataFrame(level, columns=['Level'])], axis=1)

drop_col = summary['name'][(summary['Level'] <= 1) | (summary['Missing Percentage'] >= 0.8)]
data.drop(columns=drop_col, inplace=True)
print(">>>> Data Shape : {}".format(data.shape))

>>>> Data Shape : (532, 22)


In [7]:
drop_col

10    zprior
Name: name, dtype: object

In [8]:
summary

name  Missing Percentage  Level
0    censor                 0.0      2
1     event                 0.0    358
2       age                 0.0     52
3      wtkg                 0.0    312
4      hemo                 0.0      2
5      homo                 0.0      2
6     drugs                 0.0      2
7    karnof                 0.0      4
8    oprior                 0.0      2
9       z30                 0.0      2
10   zprior                 0.0      1
11  preanti                 0.0    273
12     race                 0.0      2
13   gender                 0.0      2
14     str2                 0.0      2
15    strat                 0.0      3
16  symptom                 0.0      2
17     cd40                 0.0    278
18    cd420                 0.0    314
19    cd496                 0.0    231
20        r                 0.0      2
21     cd80                 0.0    416
22    cd820                 0.0    423

In [9]:
# X's & Y Split
Y = data['censor']
X = data.drop(columns=['censor'])

In [10]:
idx = list(range(X.shape[0]))
train_idx, valid_idx = train_test_split(idx, test_size=0.3, random_state=2021)
print(">>>> # of Train data : {}".format(len(train_idx)))
print(">>>> # of valid data : {}".format(len(valid_idx)))
print(">>>> # of Train data Y : {}".format(Counter(Y.iloc[train_idx])))
print(">>>> # of valid data Y : {}".format(Counter(Y.iloc[valid_idx])))

>>>> # of Train data : 372
>>>> # of valid data : 160
>>>> # of Train data Y : Counter({0: 241, 1: 131})
>>>> # of valid data Y : Counter({0: 110, 1: 50})


In [11]:
# n_estimators
n_tree = [5, 10, 20]
# learning_rate
l_rate = [0.1, 0.3]
# max_depth
m_depth = [3, 5]
# reg_alpha
L1_norm = [0.1, 0.3, 0.5]

# Modeling
save_n = []
save_l = []
save_m = []
save_L1 = []
f1_score_ = []

cnt = 0

for n in n_tree:
    for l in l_rate:
        for m in m_depth:
            for L1 in L1_norm:
                
                print(">>> {} <<<".format(cnt))
                cnt +=1
                print("n_estimators : {}, learning_rate : {}, max_depth : {}, reg_alpha : {}".format(n, l, m, L1))
                model = XGBClassifier(n_estimators=n, learning_rate=l, 
                                      max_depth=m, reg_alpha=L1, objective='binary:logistic', random_state=119)
                model.fit(X.iloc[train_idx], Y.iloc[train_idx])
                
                
                # Train Acc
                y_pre_train = model.predict(X.iloc[train_idx])
                cm_train = confusion_matrix(Y.iloc[train_idx], y_pre_train)
                print("Train Confusion Matrix")
                print(cm_train)
                print("Train Acc : {}".format((cm_train[0,0] + cm_train[1,1])/cm_train.sum()))
                print("Train F1-Score : {}".format(f1_score(Y.iloc[train_idx], y_pre_train)))

                # Test Acc
                y_pre_test = model.predict(X.iloc[valid_idx])
                cm_test = confusion_matrix(Y.iloc[valid_idx], y_pre_test)
                print("Test Confusion Matrix")
                print(cm_test)
                print("TesT Acc : {}".format((cm_test[0,0] + cm_test[1,1])/cm_test.sum()))
                print("Test F1-Score : {}".format(f1_score(Y.iloc[valid_idx], y_pre_test)))
                print("-----------------------------------------------------------------------")
                print("-----------------------------------------------------------------------")
                save_n.append(n)
                save_l.append(l)
                save_m.append(m)
                save_L1.append(L1)
                f1_score_.append(f1_score(Y.iloc[valid_idx], y_pre_test))
                
                # Model 저장
                #import joblib
                #joblib.dump(model, './XGBoost_model/Result_{}_{}_{}_{}_{}.pkl'.format(n, l, m, L1, round(f1_score_[-1], 4)))
                #gc.collect()

>>> 0 <<<
n_estimators : 5, learning_rate : 0.1, max_depth : 3, reg_alpha : 0.1
Train Confusion Matrix
[[230  11]
 [ 29 102]]
Train Acc : 0.8924731182795699
Train F1-Score : 0.8360655737704918
Test Confusion Matrix
[[97 13]
 [ 2 48]]
TesT Acc : 0.90625
Test F1-Score : 0.8648648648648649
-----------------------------------------------------------------------
-----------------------------------------------------------------------
>>> 1 <<<
n_estimators : 5, learning_rate : 0.1, max_depth : 3, reg_alpha : 0.3
Train Confusion Matrix
[[230  11]
 [ 30 101]]
Train Acc : 0.8897849462365591
Train F1-Score : 0.831275720164609
Test Confusion Matrix
[[97 13]
 [ 2 48]]
TesT Acc : 0.90625
Test F1-Score : 0.8648648648648649
-----------------------------------------------------------------------
-----------------------------------------------------------------------
>>> 2 <<<
n_estimators : 5, learning_rate : 0.1, max_depth : 3, reg_alpha : 0.5
Train Confusion Matrix
[[230  11]
 [ 31 100]]
Train Acc :

In [12]:
print(">>> {} <<<\nBest Test f1-score : {}\nBest n_estimators : {}\nBest Learning Rate : {}\nBest Max_depth : {}\nBest L1-norm : {}".format(np.argmax(f1_score_),
                                                                                                                                            f1_score_[np.argmax(f1_score_)], 
                                                                                                                                            save_n[np.argmax(f1_score_)],
                                                                                                                                            save_l[np.argmax(f1_score_)],
                                                                                                                                            save_m[np.argmax(f1_score_)],
                                                                                                                                            save_L1[np.argmax(f1_score_)]))

>>> 0 <<<
Best Test f1-score : 0.8648648648648649
Best n_estimators : 5
Best Learning Rate : 0.1
Best Max_depth : 3
Best L1-norm : 0.1


In [13]:
best_model = XGBClassifier(n_estimators=save_n[np.argmax(f1_score_)], learning_rate=save_l[np.argmax(f1_score_)], 
                           max_depth=save_m[np.argmax(f1_score_)], reg_alpha=save_L1[np.argmax(f1_score_)], objective='binary:logistic', 
                           random_state=119)
best_model.fit(X.iloc[train_idx], Y.iloc[train_idx])

# Train Acc
y_pre_train = best_model.predict(X.iloc[train_idx])
cm_train = confusion_matrix(Y.iloc[train_idx], y_pre_train)
print("Train Confusion Matrix")
print(cm_train)
print("Train Acc : {}".format((cm_train[0,0] + cm_train[1,1])/cm_train.sum()))
print("Train F1-Score : {}".format(f1_score(Y.iloc[train_idx], y_pre_train)))

# Test Acc
y_pre_test = best_model.predict(X.iloc[valid_idx])
cm_test = confusion_matrix(Y.iloc[valid_idx], y_pre_test)
print("Test Confusion Matrix")
print(cm_test)
print("TesT Acc : {}".format((cm_test[0,0] + cm_test[1,1])/cm_test.sum()))
print("Test F1-Score : {}".format(f1_score(Y.iloc[valid_idx], y_pre_test)))

Train Confusion Matrix
[[230  11]
 [ 29 102]]
Train Acc : 0.8924731182795699
Train F1-Score : 0.8360655737704918
Test Confusion Matrix
[[97 13]
 [ 2 48]]
TesT Acc : 0.90625
Test F1-Score : 0.8648648648648649
